import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nv className="flex items-center justify-between px-6  bg-sky-400">
          <Link href="/" className="font-bold text-4xl">Next</Link>
          <div className="flex gap-5 ">
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/user">user</Link>
          </div>
        </nv>
        {children}
      </body>
    </html>
  );
}